from . import element as element
from . import fhirtypes as fhirtypes

class Extension(element.Element):
    __resource_type__: str = "Extension"
    url: fhirtypes.UriType | None = None
    valueAddress: fhirtypes.AddressType | None = None
    valueAge: fhirtypes.AgeType | None = None
    valueAnnotation: fhirtypes.AnnotationType | None = None
    valueAttachment: fhirtypes.AttachmentType | None = None
    valueBase64Binary: fhirtypes.Base64BinaryType | None = None
    valueBoolean: bool | None = None
    valueCanonical: fhirtypes.CanonicalType | None = None
    valueCode: fhirtypes.CodeType | None = None
    valueCodeableConcept: fhirtypes.CodeableConceptType | None = None
    valueCodeableReference: fhirtypes.CodeableReferenceType | None = None
    valueCoding: fhirtypes.CodingType | None = None
    valueContactDetail: fhirtypes.ContactDetailType | None = None
    valueContactPoint: fhirtypes.ContactPointType | None = None
    valueContributor: fhirtypes.ContributorType | None = None
    valueCount: fhirtypes.CountType | None = None
    valueDataRequirement: fhirtypes.DataRequirementType | None = None
    valueDate: fhirtypes.DateType | None = None
    valueDateTime: fhirtypes.DateTimeType | None = None
    valueDecimal: fhirtypes.DecimalType | None = None
    valueDistance: fhirtypes.DistanceType | None = None
    valueDosage: fhirtypes.DosageType | None = None
    valueDuration: fhirtypes.DurationType | None = None
    valueExpression: fhirtypes.ExpressionType | None = None
    valueHumanName: fhirtypes.HumanNameType | None = None
    valueId: fhirtypes.IdType | None = None
    valueIdentifier: fhirtypes.IdentifierType | None = None
    valueInstant: fhirtypes.InstantType | None = None
    valueInteger: fhirtypes.IntegerType | None = None
    valueMarkdown: fhirtypes.MarkdownType | None = None
    valueMoney: fhirtypes.MoneyType | None = None
    valueOid: fhirtypes.OidType | None = None
    valueParameterDefinition: fhirtypes.ParameterDefinitionType | None = None
    valuePeriod: fhirtypes.PeriodType | None = None
    valuePositiveInt: fhirtypes.PositiveIntType | None = None
    valueQuantity: fhirtypes.QuantityType | None = None
    valueRange: fhirtypes.RangeType | None = None
    valueRatio: fhirtypes.RatioType | None = None
    valueRatioRange: fhirtypes.RatioRangeType | None = None
    valueReference: fhirtypes.ReferenceType | None = None
    valueRelatedArtifact: fhirtypes.RelatedArtifactType | None = None
    valueSampledData: fhirtypes.SampledDataType | None = None
    valueSignature: fhirtypes.SignatureType | None = None
    valueString: fhirtypes.StringType | None = None
    valueTime: fhirtypes.TimeType | None = None
    valueTiming: fhirtypes.TimingType | None = None
    valueTriggerDefinition: fhirtypes.TriggerDefinitionType | None = None
    valueUnsignedInt: fhirtypes.UnsignedIntType | None = None
    valueUri: fhirtypes.UriType | None = None
    valueUrl: fhirtypes.UrlType | None = None
    valueUsageContext: fhirtypes.UsageContextType | None = None
    valueUuid: fhirtypes.UuidType | None = None
    @classmethod
    def elements_sequence(cls) -> list[str]: ...
    def get_one_of_many_fields(self) -> dict[str, list[str]]: ...
