# mypy: ignore-errors
import httpx
from langfuse import Langfuse as Langfuse
from langfuse.types import MaskFunction as MaskFunction

class LangfuseSingleton:
    def __new__(cls): ...
    def get(self, *, public_key: str | None = None, secret_key: str | None = None, host: str | None = None, release: str | None = None, debug: bool | None = None, threads: int | None = None, flush_at: int | None = None, flush_interval: int | None = None, max_retries: int | None = None, timeout: int | None = None, httpx_client: httpx.Client | None = None, sdk_integration: str | None = None, enabled: bool | None = None, sample_rate: float | None = None, mask: MaskFunction | None = None, environment: str | None = None) -> Langfuse: ...
    def reset(self) -> None: ...
