from _typeshed import Incomplete
from google.cloud.bigquery.encryption_configuration import EncryptionConfiguration as EncryptionConfiguration
from google.cloud.bigquery.job.base import _AsyncJob, _JobConfig
from google.cloud.bigquery.table import TableReference as TableReference

class OperationType:
    OPERATION_TYPE_UNSPECIFIED: str
    COPY: str
    SNAPSHOT: str
    CLONE: str
    RESTORE: str

class CopyJobConfig(_JobConfig):
    def __init__(self, **kwargs) -> None: ...
    @property
    def create_disposition(self): ...
    @create_disposition.setter
    def create_disposition(self, value) -> None: ...
    @property
    def write_disposition(self): ...
    @write_disposition.setter
    def write_disposition(self, value) -> None: ...
    @property
    def destination_encryption_configuration(self): ...
    @destination_encryption_configuration.setter
    def destination_encryption_configuration(self, value) -> None: ...
    @property
    def operation_type(self) -> str: ...
    @operation_type.setter
    def operation_type(self, value: str | None): ...
    @property
    def destination_expiration_time(self) -> str: ...
    @destination_expiration_time.setter
    def destination_expiration_time(self, value: str): ...

class CopyJob(_AsyncJob):
    def __init__(self, job_id, sources, destination, client, job_config: Incomplete | None = None) -> None: ...
    @property
    def configuration(self) -> CopyJobConfig: ...
    @property
    def destination(self): ...
    @property
    def sources(self): ...
    @property
    def create_disposition(self): ...
    @property
    def write_disposition(self): ...
    @property
    def destination_encryption_configuration(self): ...
    def to_api_repr(self): ...
    @classmethod
    def from_api_repr(cls, resource, client): ...
