from .pydantic_utilities import pydantic_v1 as pydantic_v1
from typing import Any

def traverse_query_dict(dict_flat: dict[str, Any], key_prefix: str | None = None) -> dict[str, Any]: ...
def single_query_encoder(query_key: str, query_value: Any) -> dict[str, Any]: ...
def encode_query(query: dict[str, Any] | None) -> dict[str, Any] | None: ...
