# mypy: ignore-errors

from _typeshed import Incomplete
from google.cloud.exceptions import NotFound as NotFound
from google.cloud.storage._opentelemetry_tracing import create_trace_span as create_trace_span
from google.cloud.storage.retry import DEFAULT_RETRY as DEFAULT_RETRY
from google.cloud.storage.retry import DEFAULT_RETRY_IF_ETAG_IN_JSON as DEFAULT_RETRY_IF_ETAG_IN_JSON

class HMACKeyMetadata:
    ACTIVE_STATE: str
    INACTIVE_STATE: str
    DELETED_STATE: str
    def __init__(
        self,
        client,
        access_id: Incomplete | None = None,
        project_id: Incomplete | None = None,
        user_project: Incomplete | None = None,
    ) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    @property
    def access_id(self): ...
    @property
    def etag(self): ...
    @property
    def id(self): ...
    @property
    def project(self): ...
    @property
    def service_account_email(self): ...
    @property
    def state(self): ...
    @state.setter
    def state(self, value) -> None: ...
    @property
    def time_created(self): ...
    @property
    def updated(self): ...
    @property
    def path(self): ...
    @property
    def user_project(self): ...
    def exists(self, timeout=..., retry=...): ...
    def reload(self, timeout=..., retry=...) -> None: ...
    def update(self, timeout=..., retry=...) -> None: ...
    def delete(self, timeout=..., retry=...) -> None: ...
