import urllib3.response
from google.cloud.storage._media import _download
from google.cloud.storage._media.requests import _request_helpers
from google.cloud.storage.exceptions import DataCorruption as DataCorruption

class Download(_request_helpers.RequestsMixin, _download.Download):
    def consume(self, transport, timeout=...): ...

class RawDownload(_request_helpers.RawRequestsMixin, _download.Download):
    def consume(self, transport, timeout=...): ...

class ChunkedDownload(_request_helpers.RequestsMixin, _download.ChunkedDownload):
    def consume_next_chunk(self, transport, timeout=...): ...

class RawChunkedDownload(_request_helpers.RawRequestsMixin, _download.ChunkedDownload):
    def consume_next_chunk(self, transport, timeout=...): ...

class _GzipDecoder(urllib3.response.GzipDecoder):
    def __init__(self, checksum) -> None: ...
    def decompress(self, data): ...

class _BrotliDecoder:
    def __init__(self, checksum) -> None: ...
    def decompress(self, data): ...
    def flush(self): ...
