from _typeshed import Incomplete
from google.cloud import bigquery as bigquery
from google.cloud.bigquery import query as query
from google.cloud.bigquery import table as table
from google.cloud.bigquery.dbapi import exceptions as exceptions

type_parameters_re: Incomplete

def scalar_to_query_parameter(
    value, name: Incomplete | None = None, query_parameter_type: Incomplete | None = None
): ...
def array_to_query_parameter(value, name: Incomplete | None = None, query_parameter_type: Incomplete | None = None): ...

SCALAR: Incomplete
ARRAY: Incomplete
STRUCT: Incomplete

def complex_query_parameter_type(name: str | None, type_: str, base: str): ...
def complex_query_parameter(name: str | None, value, type_: str, base: str | None = None): ...
def to_query_parameters_list(parameters, parameter_types): ...
def to_query_parameters_dict(parameters, query_parameter_types): ...
def to_query_parameters(parameters, parameter_types): ...
def bigquery_scalar_type(value): ...
def array_like(value): ...
def to_bq_table_rows(rows_iterable): ...
def raise_on_closed(exc_msg, exc_class=..., closed_attr_name: str = "_closed"): ...
