from google.cloud.storage import retry as retry
from google.cloud.storage.exceptions import InvalidResponse as InvalidResponse

RANGE_HEADER: str
CONTENT_RANGE_HEADER: str
CONTENT_ENCODING_HEADER: str

def do_nothing() -> None: ...
def header_required(response, name, get_headers, callback=...): ...
def require_status_code(response, status_codes, get_status_code, callback=...): ...
def prepare_checksum_digest(digest_bytestring): ...
def add_query_parameters(media_url, query_params): ...

class _DoNothingHash:
    def update(self, unused_chunk) -> None: ...
