from ...core.api_error import ApiError as ApiError
from ...core.client_wrapper import AsyncClientWrapper as AsyncClientWrapper, SyncClientWrapper as SyncClientWrapper
from ...core.jsonable_encoder import jsonable_encoder as jsonable_encoder
from ...core.pydantic_utilities import pydantic_v1 as pydantic_v1
from ...core.request_options import RequestOptions as RequestOptions
from ..commons.errors.access_denied_error import AccessDeniedError as AccessDeniedError
from ..commons.errors.error import Error as Error
from ..commons.errors.method_not_allowed_error import MethodNotAllowedError as MethodNotAllowedError
from ..commons.errors.not_found_error import NotFoundError as NotFoundError
from ..commons.errors.unauthorized_error import UnauthorizedError as UnauthorizedError
from ..commons.types.model import Model as Model
from .types.create_model_request import CreateModelRequest as CreateModelRequest
from .types.paginated_models import PaginatedModels as PaginatedModels
from _typeshed import Incomplete

OMIT: Incomplete

class ModelsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper) -> None: ...
    def create(self, *, request: CreateModelRequest, request_options: RequestOptions | None = None) -> Model: ...
    def list(self, *, page: int | None = None, limit: int | None = None, request_options: RequestOptions | None = None) -> PaginatedModels: ...
    def get(self, id: str, *, request_options: RequestOptions | None = None) -> Model: ...
    def delete(self, id: str, *, request_options: RequestOptions | None = None) -> None: ...

class AsyncModelsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper) -> None: ...
    async def create(self, *, request: CreateModelRequest, request_options: RequestOptions | None = None) -> Model: ...
    async def list(self, *, page: int | None = None, limit: int | None = None, request_options: RequestOptions | None = None) -> PaginatedModels: ...
    async def get(self, id: str, *, request_options: RequestOptions | None = None) -> Model: ...
    async def delete(self, id: str, *, request_options: RequestOptions | None = None) -> None: ...
