from _typeshed import Incomplete
from dateutil import relativedelta
from google.cloud._helpers import UTC as UTC

TimeoutType = float | None
BIGQUERY_EMULATOR_HOST: str

class CellDataParser:
    def to_py(self, resource, field): ...
    def bool_to_py(self, value, field): ...
    def boolean_to_py(self, value, field): ...
    def integer_to_py(self, value, field): ...
    def int64_to_py(self, value, field): ...
    def interval_to_py(self, value: str | None, field) -> relativedelta.relativedelta | None: ...
    def float_to_py(self, value, field): ...
    def float64_to_py(self, value, field): ...
    def numeric_to_py(self, value, field): ...
    def bignumeric_to_py(self, value, field): ...
    def string_to_py(self, value, _): ...
    def geography_to_py(self, value, _): ...
    def bytes_to_py(self, value, field): ...
    def timestamp_to_py(self, value, field): ...
    def datetime_to_py(self, value, field): ...
    def date_to_py(self, value, field): ...
    def time_to_py(self, value, field): ...
    def record_to_py(self, value, field): ...
    def struct_to_py(self, value, field): ...
    def json_to_py(self, value, field): ...
    def range_to_py(self, value, field): ...

CELL_DATA_PARSER: Incomplete

class DataFrameCellDataParser(CellDataParser):
    def json_to_py(self, value, _): ...

DATA_FRAME_CELL_DATA_PARSER: Incomplete

class ScalarQueryParamParser(CellDataParser):
    def timestamp_to_py(self, value, field): ...

SCALAR_QUERY_PARAM_PARSER: Incomplete
