from _typeshed import Incomplete

class EncryptionConfiguration:
    def __init__(self, kms_key_name: Incomplete | None = None) -> None: ...
    @property
    def kms_key_name(self): ...
    @kms_key_name.setter
    def kms_key_name(self, value) -> None: ...
    @classmethod
    def from_api_repr(cls, resource): ...
    def to_api_repr(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...
