class BigQueryError(Exception): ...
class LegacyBigQueryStorageError(BigQueryError): ...
class LegacyPyarrowError(BigQueryError): ...
class BigQueryStorageNotFoundError(BigQueryError): ...
class LegacyPandasError(BigQueryError): ...
